<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Title</title>
</head>
<body>
    <p>
        {{$email}}
    </p>
    <p>
        {{$password}}
    </p>
    <p>
        {{$csrf}}
    </p>
    <p>
        {{$remember_me}}
    </p>
</body>
</html>
